---
title: |
  | ECON 4101 Econometrics
  | CM19 and CM 20 Homework
author: "Pranav Singh"
date: "April 3, 2017"
output: pdf_document
# output: html_document
# output: github_document
---

```{r, include=F}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=T)
options(scipen=999)

library(ggplot2)
library(gridExtra)
require(data.table)
theme_set(theme_bw())

require(xlsx)
require(lmtest)
require(sandwich)
```

```{r, message=F}
df <- read.xlsx('../../Data/wheat.xlsx', 1, colIndex = 1:3)
str(df)
```

# Part 1: CM19
## Problem 1
```{r}
mod1 <- lm(qty ~ price + trend, df)
summary(mod1)
```

## Problem 2
```{r}
plot(mod1, 1)
```

## Problem 3
```{r}
gqtest(qty ~ price + trend, order.by = -df$trend, data = df)
```

## Problem 4
```{r}
se.uncorrected <- confint(mod1); se.uncorrected
# se.corrected <- mod1$coefficients + qt(.975, df=mod1$df.residual)*sqrt(diag(vcovHC(mod1, 'HC0'))) %*% t(c(-1,1)); se.corrected
se.robust <- coefci(mod1, vcov = vcovHC(mod1, 'HC0')); se.robust
coeftest(mod1, vcov = vcovHC(mod1, 'HC0'))
```

# Part 2: CM20
## Problem 1

#### Approach 1: Weighted Least Squares
```{r}
df1 <- df[1:13,]
df2 <- df[14:26,]

m1 <- lm(qty ~ price + trend, df1)
e1.sd <- sd(m1$residuals)
m2 <- lm(qty ~ price + trend, df2)
e2.sd <- sd(m2$residuals)

w <- rep(c(1/e1.sd, 1/e2.sd), each = 13)
mod.wle <- lm(qty ~ price + trend, df, weights = w)
summary(mod.wle)
confint(mod.wle)
```
#### Approach 2: Feasible General Least Squares
```{r}
mod1 <- lm(qty ~ price + trend, df)
e <- mod1$residuals
le2 <- log(e^2)
mod2 <- lm(le2 ~ price + trend, df)
ghat <- mod2$fitted.values
hhat <- exp(ghat)
w <- 1 / sqrt(hhat)
mod.fgls <- lm(qty ~ price + trend, df, weights = w)
summary(mod.fgls)
confint(mod.fgls)
```

## Problem 2
```{r}

```

